
-- ============================================================
-- CREATE DIMENSION TABLES
-- ============================================================

CREATE OR REPLACE TABLE KARTHICKY_DB."3_GOLD".DIM_DATE (

    DATE_SK NUMBER AUTOINCREMENT,
    FULL_DATE DATE,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR,
    WEEK_OF_YEAR NUMBER,
    DAY_OF_MONTH NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME VARCHAR,
    IS_WEEKEND BOOLEAN

);

CREATE OR REPLACE TABLE KARTHICKY_DB."3_GOLD".DIM_BRANCH (

    BRANCH_SK NUMBER AUTOINCREMENT,
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    DISTRICT VARCHAR,
    PROVINCE VARCHAR,

    _IS_CURRENT BOOLEAN DEFAULT TRUE,
    _EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ

);

CREATE OR REPLACE TABLE KARTHICKY_DB."3_GOLD".DIM_CUSTOMER (

    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_KEY STRING,

    CUSTOMER_GENDER VARCHAR,
    CUSTOMER_AGE NUMBER,
    CUSTOMER_CITY VARCHAR,

    _IS_CURRENT BOOLEAN DEFAULT TRUE,
    _EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ

);

CREATE OR REPLACE TABLE KARTHICKY_DB."3_GOLD".DIM_MEDICINE (

    MEDICINE_SK NUMBER AUTOINCREMENT,
    MEDICINE_ID NUMBER,
    MEDICINE_NAME VARCHAR,
    GENERIC_NAME VARCHAR,
    MEDICINE_CATEGORY VARCHAR,

    _IS_CURRENT BOOLEAN DEFAULT TRUE,
    _EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ

);

CREATE OR REPLACE TABLE KARTHICKY_DB."3_GOLD".DIM_SUPPLIER (

    SUPPLIER_SK NUMBER AUTOINCREMENT,

    SUPPLIER_NAME VARCHAR,

    _IS_CURRENT BOOLEAN DEFAULT TRUE,
    _EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ

);
