
CREATE OR REPLACE TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_GOLD_DIMS

WAREHOUSE = COMPUTE_WH
SCHEDULE = '2 MINUTE'

WHEN SYSTEM$STREAM_HAS_DATA(
'KARTHICKY_DB."2_SILVER".STREAM_SILVER_TO_GOLD'
)

AS

BEGIN

CREATE OR REPLACE TEMP TABLE KARTHICKY_DB."3_GOLD".STG_SILVER AS
SELECT *
FROM KARTHICKY_DB."2_SILVER".STREAM_SILVER_TO_GOLD;

-- DIM_BRANCH: expire changed rows
UPDATE KARTHICKY_DB."3_GOLD".DIM_BRANCH tgt
SET tgt._IS_CURRENT = FALSE,
    tgt._EFFECTIVE_TO = CURRENT_TIMESTAMP()
WHERE tgt._IS_CURRENT = TRUE
AND EXISTS (
    SELECT 1 FROM (
        SELECT DISTINCT BRANCH_ID, BRANCH_NAME, DISTRICT, PROVINCE
        FROM KARTHICKY_DB."3_GOLD".STG_SILVER
    ) src
    WHERE src.BRANCH_ID = tgt.BRANCH_ID
    AND (src.BRANCH_NAME != tgt.BRANCH_NAME
         OR src.DISTRICT != tgt.DISTRICT
         OR src.PROVINCE != tgt.PROVINCE)
);

-- DIM_BRANCH: insert new/changed rows
MERGE INTO KARTHICKY_DB."3_GOLD".DIM_BRANCH tgt
USING (
SELECT DISTINCT BRANCH_ID, BRANCH_NAME, DISTRICT, PROVINCE
FROM KARTHICKY_DB."3_GOLD".STG_SILVER
) src
ON tgt.BRANCH_ID = src.BRANCH_ID
AND tgt._IS_CURRENT = TRUE
AND tgt.BRANCH_NAME = src.BRANCH_NAME
AND tgt.DISTRICT = src.DISTRICT
AND tgt.PROVINCE = src.PROVINCE
WHEN NOT MATCHED THEN
INSERT (BRANCH_ID, BRANCH_NAME, DISTRICT, PROVINCE)
VALUES (src.BRANCH_ID, src.BRANCH_NAME, src.DISTRICT, src.PROVINCE);

-- DIM_CUSTOMER: expire changed rows
UPDATE KARTHICKY_DB."3_GOLD".DIM_CUSTOMER tgt
SET tgt._IS_CURRENT = FALSE,
    tgt._EFFECTIVE_TO = CURRENT_TIMESTAMP()
WHERE tgt._IS_CURRENT = TRUE
AND EXISTS (
    SELECT 1 FROM (
        SELECT DISTINCT
        SHA2(CONCAT_WS('|', TRANSACTION_ID, CUSTOMER_CITY, CUSTOMER_AGE)) AS CUSTOMER_KEY,
        CUSTOMER_GENDER,
        CUSTOMER_AGE,
        CUSTOMER_CITY
        FROM KARTHICKY_DB."3_GOLD".STG_SILVER
    ) src
    WHERE src.CUSTOMER_KEY = tgt.CUSTOMER_KEY
    AND (src.CUSTOMER_GENDER != tgt.CUSTOMER_GENDER
         OR src.CUSTOMER_AGE != tgt.CUSTOMER_AGE
         OR src.CUSTOMER_CITY != tgt.CUSTOMER_CITY)
);

-- DIM_CUSTOMER: insert new/changed rows
MERGE INTO KARTHICKY_DB."3_GOLD".DIM_CUSTOMER tgt
USING (
SELECT DISTINCT
SHA2(CONCAT_WS('|', TRANSACTION_ID, CUSTOMER_CITY, CUSTOMER_AGE)) AS CUSTOMER_KEY,
CUSTOMER_GENDER,
CUSTOMER_AGE,
CUSTOMER_CITY
FROM KARTHICKY_DB."3_GOLD".STG_SILVER
) src
ON tgt.CUSTOMER_KEY = src.CUSTOMER_KEY
AND tgt._IS_CURRENT = TRUE
AND tgt.CUSTOMER_GENDER = src.CUSTOMER_GENDER
AND tgt.CUSTOMER_AGE = src.CUSTOMER_AGE
AND tgt.CUSTOMER_CITY = src.CUSTOMER_CITY
WHEN NOT MATCHED THEN
INSERT (CUSTOMER_KEY, CUSTOMER_GENDER, CUSTOMER_AGE, CUSTOMER_CITY)
VALUES (src.CUSTOMER_KEY, src.CUSTOMER_GENDER, src.CUSTOMER_AGE, src.CUSTOMER_CITY);

-- DIM_MEDICINE: expire changed rows
UPDATE KARTHICKY_DB."3_GOLD".DIM_MEDICINE tgt
SET tgt._IS_CURRENT = FALSE,
    tgt._EFFECTIVE_TO = CURRENT_TIMESTAMP()
WHERE tgt._IS_CURRENT = TRUE
AND EXISTS (
    SELECT 1 FROM (
        SELECT DISTINCT MEDICINE_ID, MEDICINE_NAME, GENERIC_NAME, MEDICINE_CATEGORY
        FROM KARTHICKY_DB."3_GOLD".STG_SILVER
    ) src
    WHERE src.MEDICINE_ID = tgt.MEDICINE_ID
    AND (src.MEDICINE_NAME != tgt.MEDICINE_NAME
         OR src.GENERIC_NAME != tgt.GENERIC_NAME
         OR src.MEDICINE_CATEGORY != tgt.MEDICINE_CATEGORY)
);

-- DIM_MEDICINE: insert new/changed rows
MERGE INTO KARTHICKY_DB."3_GOLD".DIM_MEDICINE tgt
USING (
SELECT DISTINCT MEDICINE_ID, MEDICINE_NAME, GENERIC_NAME, MEDICINE_CATEGORY
FROM KARTHICKY_DB."3_GOLD".STG_SILVER
) src
ON tgt.MEDICINE_ID = src.MEDICINE_ID
AND tgt._IS_CURRENT = TRUE
AND tgt.MEDICINE_NAME = src.MEDICINE_NAME
AND tgt.GENERIC_NAME = src.GENERIC_NAME
AND tgt.MEDICINE_CATEGORY = src.MEDICINE_CATEGORY
WHEN NOT MATCHED THEN
INSERT (MEDICINE_ID, MEDICINE_NAME, GENERIC_NAME, MEDICINE_CATEGORY)
VALUES (src.MEDICINE_ID, src.MEDICINE_NAME, src.GENERIC_NAME, src.MEDICINE_CATEGORY);

-- DIM_SUPPLIER: insert only (no SCD2 attributes to track beyond name)
MERGE INTO KARTHICKY_DB."3_GOLD".DIM_SUPPLIER tgt
USING (
SELECT DISTINCT SUPPLIER_NAME
FROM KARTHICKY_DB."3_GOLD".STG_SILVER
) src
ON tgt.SUPPLIER_NAME = src.SUPPLIER_NAME
AND tgt._IS_CURRENT = TRUE
WHEN NOT MATCHED THEN
INSERT (SUPPLIER_NAME)
VALUES (src.SUPPLIER_NAME);

INSERT INTO KARTHICKY_DB."2_SILVER".PIPELINE_AUDIT_LOG
    (TASK_NAME, LAYER, ACTION, ROWS_PROCESSED, STATUS)
VALUES
    ('TASK_LOAD_GOLD_DIMS', 'GOLD', 'SCD2_MERGE', (SELECT COUNT(*) FROM KARTHICKY_DB."3_GOLD".STG_SILVER), 'SUCCESS');

END;
