
CREATE OR REPLACE TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_FACT_SALES

WAREHOUSE = COMPUTE_WH
SCHEDULE = '2 MINUTE'

WHEN SYSTEM$STREAM_HAS_DATA(
'KARTHICKY_DB."2_SILVER".STREAM_SILVER_TO_FACT'
)

AS

BEGIN

CREATE OR REPLACE TEMP TABLE KARTHICKY_DB."3_GOLD".STG_FACT AS
SELECT *
FROM KARTHICKY_DB."2_SILVER".STREAM_SILVER_TO_FACT;

MERGE INTO KARTHICKY_DB."3_GOLD".FACT_SALES tgt

USING (

SELECT

s.*,

SHA2(
CONCAT_WS('|',
s.TRANSACTION_ID,
s.MEDICINE_ID,
s.BRANCH_ID
)
) AS FACT_HASH,

COALESCE(b.BRANCH_SK, -1) AS LKP_BRANCH_SK,
COALESCE(c.CUSTOMER_SK, -1) AS LKP_CUSTOMER_SK,
COALESCE(m.MEDICINE_SK, -1) AS LKP_MEDICINE_SK,
COALESCE(sp.SUPPLIER_SK, -1) AS LKP_SUPPLIER_SK

FROM KARTHICKY_DB."3_GOLD".STG_FACT s

LEFT JOIN KARTHICKY_DB."3_GOLD".DIM_BRANCH b
    ON b.BRANCH_ID = s.BRANCH_ID AND b._IS_CURRENT = TRUE

LEFT JOIN KARTHICKY_DB."3_GOLD".DIM_CUSTOMER c
    ON c.CUSTOMER_KEY = SHA2(CONCAT_WS('|', s.TRANSACTION_ID, s.CUSTOMER_CITY, s.CUSTOMER_AGE))
    AND c._IS_CURRENT = TRUE

LEFT JOIN KARTHICKY_DB."3_GOLD".DIM_MEDICINE m
    ON m.MEDICINE_ID = s.MEDICINE_ID AND m._IS_CURRENT = TRUE

LEFT JOIN KARTHICKY_DB."3_GOLD".DIM_SUPPLIER sp
    ON sp.SUPPLIER_NAME = s.SUPPLIER_NAME AND sp._IS_CURRENT = TRUE

) src

ON tgt.FACT_HASH = src.FACT_HASH

WHEN MATCHED
AND src._IS_SOFT_DELETED = TRUE

THEN UPDATE SET

tgt._IS_SOFT_DELETED = TRUE

WHEN NOT MATCHED

THEN INSERT (

TRANSACTION_ID,
BRANCH_SK,
CUSTOMER_SK,
MEDICINE_SK,
SUPPLIER_SK,
QUANTITY,
LINE_TOTAL_LKR,
FACT_HASH

)

VALUES (

src.TRANSACTION_ID,
src.LKP_BRANCH_SK,
src.LKP_CUSTOMER_SK,
src.LKP_MEDICINE_SK,
src.LKP_SUPPLIER_SK,
src.QUANTITY,
src.LINE_TOTAL_LKR,
src.FACT_HASH

);

INSERT INTO KARTHICKY_DB."2_SILVER".PIPELINE_AUDIT_LOG
    (TASK_NAME, LAYER, ACTION, ROWS_PROCESSED, ROWS_INSERTED, STATUS)
VALUES
    ('TASK_LOAD_FACT_SALES', 'GOLD', 'FACT_MERGE', (SELECT COUNT(*) FROM KARTHICKY_DB."3_GOLD".STG_FACT), SQLROWCOUNT, 'SUCCESS');

END;
