
-- ============================================================
-- RESUME TASKS
-- ============================================================

ALTER TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_FACT_SALES RESUME;

ALTER TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_GOLD_DIMS RESUME;

ALTER TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_SILVER RESUME;

ALTER TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_BRONZE RESUME;
