
-- ============================================================
-- CREATE SILVER TABLE
-- ============================================================

CREATE OR REPLACE TABLE KARTHICKY_DB."2_SILVER".PHARMA_SALES_CLEAN (

    SILVER_ID NUMBER AUTOINCREMENT,

    TRANSACTION_ID NUMBER,
    TRANSACTION_DATE DATE,

    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    DISTRICT VARCHAR,
    PROVINCE VARCHAR,

    PAYMENT_METHOD VARCHAR,

    CUSTOMER_GENDER VARCHAR,
    CUSTOMER_AGE NUMBER,
    CUSTOMER_CITY VARCHAR,

    MEDICINE_ID NUMBER,
    MEDICINE_NAME VARCHAR,
    GENERIC_NAME VARCHAR,
    MEDICINE_CATEGORY VARCHAR,
    DOSAGE_FORM VARCHAR,
    STRENGTH_MG VARCHAR,
    PACK_SIZE NUMBER,

    SUPPLIER_NAME VARCHAR,

    PRESCRIPTION_REQUIRED BOOLEAN,

    BATCH_NO VARCHAR,
    EXPIRY_DATE DATE,

    QUANTITY NUMBER,
    UNIT_PRICE_LKR NUMBER(18,2),
    DISCOUNT_RATE NUMBER(10,4),
    LINE_TOTAL_LKR NUMBER(18,2),

    YEAR NUMBER,
    MONTH NUMBER,

    _HASH_DIFF STRING,

    _IS_SOFT_DELETED BOOLEAN DEFAULT FALSE,

    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);
