
-- ============================================================
-- CREATE AUDIT LOG TABLE
-- ============================================================

CREATE OR REPLACE TABLE KARTHICKY_DB."2_SILVER".PIPELINE_AUDIT_LOG (

    AUDIT_ID NUMBER AUTOINCREMENT,

    TASK_NAME VARCHAR,
    LAYER VARCHAR,
    ACTION VARCHAR,

    ROWS_PROCESSED NUMBER DEFAULT 0,
    ROWS_INSERTED NUMBER DEFAULT 0,
    ROWS_UPDATED NUMBER DEFAULT 0,
    ROWS_REJECTED NUMBER DEFAULT 0,

    STATUS VARCHAR DEFAULT 'SUCCESS',

    ERROR_MESSAGE VARCHAR,

    BATCH_ID VARCHAR DEFAULT UUID_STRING(),

    _EXECUTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);
