
-- ============================================================
-- CREATE BRONZE TABLE
-- ============================================================

CREATE OR REPLACE TABLE KARTHICKY_DB."1_BRONZE".PHARMA_SALES_RAW (

    BRONZE_ID NUMBER AUTOINCREMENT,

    TRANSACTION_ID NUMBER,
    TRANSACTION_DATE VARCHAR,

    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    DISTRICT VARCHAR,
    PROVINCE VARCHAR,

    PAYMENT_METHOD VARCHAR,

    CUSTOMER_GENDER VARCHAR,
    CUSTOMER_AGE NUMBER,
    CUSTOMER_CITY VARCHAR,

    MEDICINE_ID NUMBER,
    MEDICINE_NAME VARCHAR,
    GENERIC_NAME VARCHAR,
    MEDICINE_CATEGORY VARCHAR,
    DOSAGE_FORM VARCHAR,
    STRENGTH_MG VARCHAR,
    PACK_SIZE NUMBER,

    SUPPLIER_NAME VARCHAR,

    PRESCRIPTION_REQUIRED VARCHAR,

    BATCH_NO VARCHAR,
    EXPIRY_DATE VARCHAR,

    QUANTITY NUMBER,
    UNIT_PRICE_LKR FLOAT,
    DISCOUNT_RATE FLOAT,
    LINE_TOTAL_LKR FLOAT,

    YEAR NUMBER,
    MONTH NUMBER,

    _CDC_ACTION VARCHAR,
    _IS_UPDATE BOOLEAN,
    _IS_SOFT_DELETED BOOLEAN DEFAULT FALSE,

    _HASH_DIFF STRING,

    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _BATCH_ID STRING DEFAULT UUID_STRING()

);
